### PR TITLE
updates to accommodate LFPy-2.2; installs neuron using pip

### LINKED ISSUE #3: Support LFPy-2.2
Hi, 
Since merging https://github.com/LFPy/LFPy/pull/226 into LFPy@master `Cell.xstart` etc. has been renamed:

> 8. `Cell` attributes `ustart, umid, uend; u in {x, y, z}` has been replaced with ndarrays `{x, y, z}` of shape `(totnsegs, 2). To get to the mid point simply issue `u.mean(axis=-1)`.
> 9. `Cell` attribute `diam` is now renamed `d` (same as in `LFPykit.GeometryCell`)

### PR DESCRIPTION
**Pull request by espenhgn**
Closes #3  - but I suggest merging only after LFPy-2.2 has been pushed to PyPI (.travis.yml looks for LFPy>=2.2).
I also fixed a bunch of syntax warnings due to comparisons using `is/is not`.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks Espen! I agree, let's wait for the Pypi package. :)

**Comment by espenhgn** [comment]
> Thanks Espen! I agree, let's wait for the Pypi package. :)

Yes, I'm just checking with some 2.2rc builds at the moment. It's slow going as travis-ci.org should be migrated to travis-ci.com, but it won't let me for some stupid reason.

**Comment by espenhgn** [comment]
Hi @alejoe91. LFPy-2.2.* is now on PyPi, conda-forge. Think this can be merged then.

**Comment by alejoe91** [comment]
And I'll make a new release 🙂

**Comment by espenhgn** [comment]
> And I'll make a new release 🙂

Great stuff! Hope to update some LFPy examples using this tool soon and allow things to become a a bit more integrated.

**Comment by alejoe91** [comment]
@espenhgn https://pypi.org/project/neuroplotlib/

Version 0.2.0 is up on PyPi!

**Comment by espenhgn** [comment]
Splendid :)

**Pull request merged**
